replicaCount: 1
image:
  repository: ghcr.io/rishabhagrawal287/microservices-platform-log-analyzer
  tag: "66452aec24c7b82b2c97bbd2411cf124673b9c4e"
  pullPolicy: IfNotPresent
service:
  port: 9092
resources:
  requests:
    cpu: 100m
    memory: 128Mi
  limits:
    cpu: 300m
    memory: 256Mi
podDisruptionBudget:
  enabled: false
ollamaModel: qwen2.5:1.5b
